from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(600, 171)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        MusicPlayer.setFont(font)
        self.PlayButton = QtWidgets.QPushButton(MusicPlayer)
        self.PlayButton.setGeometry(QtCore.QRect(0, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        self.PlayButton.setFont(font)
        self.PlayButton.setObjectName("PlayButton")
        self.PauseButton = QtWidgets.QPushButton(MusicPlayer)
        self.PauseButton.setGeometry(QtCore.QRect(150, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        self.PauseButton.setFont(font)
        self.PauseButton.setObjectName("PauseButton")
        self.VolumeSlider = QtWidgets.QSlider(MusicPlayer)
        self.VolumeSlider.setGeometry(QtCore.QRect(100, 130, 491, 22))
        self.VolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VolumeSlider.setObjectName("VolumeSlider")
        self.ResumeButton = QtWidgets.QPushButton(MusicPlayer)
        self.ResumeButton.setGeometry(QtCore.QRect(300, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        self.ResumeButton.setFont(font)
        self.ResumeButton.setObjectName("ResumeButton")
        self.StopButton = QtWidgets.QPushButton(MusicPlayer)
        self.StopButton.setGeometry(QtCore.QRect(450, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.VolumeLabel = QtWidgets.QLabel(MusicPlayer)
        self.VolumeLabel.setGeometry(QtCore.QRect(30, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.VolumeLabel.setFont(font)
        self.VolumeLabel.setObjectName("VolumeLabel")
        self.CurrentlyPlaying = QtWidgets.QLabel(MusicPlayer)
        self.CurrentlyPlaying.setGeometry(QtCore.QRect(10, 10, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        self.CurrentlyPlaying.setFont(font)
        self.CurrentlyPlaying.setObjectName("CurrentlyPlaying")

        self.retranslateUi(MusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "Music Player"))
        self.PlayButton.setText(_translate("MusicPlayer", "Play"))
        self.PauseButton.setText(_translate("MusicPlayer", "Pause"))
        self.ResumeButton.setText(_translate("MusicPlayer", "Resume"))
        self.StopButton.setText(_translate("MusicPlayer", "Stop"))
        self.VolumeLabel.setText(_translate("MusicPlayer", "Volume"))
        self.CurrentlyPlaying.setText(_translate("MusicPlayer", "Currently Playing:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MusicPlayer = QtWidgets.QDialog()
    ui = Ui_MusicPlayer()
    ui.setupUi(MusicPlayer)
    MusicPlayer.show()
    sys.exit(app.exec_())
